{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled $service.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "commercialwebsite.serviceAccountName" $ }}-{{ $serviceName }}
  labels:
    {{- include "commercialwebsite.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  {{- with $service.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
