package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"daemon/graph/model"
	"daemon/state"
	"daemon/telepresence"
	"fmt"
)

// SetServiceTarget is the resolver for the setServiceTarget mutation.
func (r *mutationResolver) SetServiceTargets(ctx context.Context, services []*model.ServiceTargetInput) ([]*model.Service, error) {
	var serviceSnapshot = state.GlobalStore.GetServices()
	var result []*model.Service
	var hasChanges = false
	var updates = make(map[string]model.ServiceTarget)

	// First, check if any services actually need to change
	for _, serviceInput := range services {
		if svcInfo, exists := serviceSnapshot[serviceInput.Name]; exists {
			if svcInfo.Target != serviceInput.Target {
				hasChanges = true
				updates[serviceInput.Name] = serviceInput.Target
			}
		}
	}

	if !hasChanges {
		// No actual changes needed, return current state
		for _, serviceInput := range services {
			if svcInfo, exists := serviceSnapshot[serviceInput.Name]; exists {
				result = append(result, &model.Service{Name: svcInfo.Name, Target: svcInfo.Target, URL: svcInfo.URL})
			}
		}
		return result, nil
	}

	// Apply all service updates and status changes in a single batch to minimize notifications
	if err := state.GlobalStore.UpdateServiceTargetsWithStatus(updates, model.ConnectionStatusConnected); err != nil {
		return nil, fmt.Errorf("failed to update service targets: %w", err)
	}

	// Handle telepresence intercept/leave operations
	for _, serviceInput := range services {
		if svcInfo, exists := state.GlobalStore.GetServices()[serviceInput.Name]; exists {
			if serviceInput.Target == model.ServiceTargetLocal && serviceSnapshot[serviceInput.Name].Target == model.ServiceTargetRemote {
				telepresence.InterceptService(svcInfo.URL)
			} else if serviceInput.Target == model.ServiceTargetRemote && serviceSnapshot[serviceInput.Name].Target == model.ServiceTargetLocal {
				telepresence.LeaveService(svcInfo.URL)
			}
			result = append(result, &model.Service{Name: svcInfo.Name, Target: serviceInput.Target, URL: svcInfo.URL})
		} else {
			return nil, fmt.Errorf("service %s not found", serviceInput.Name)
		}
	}

	return result, nil
}

// AttemptReconnect is the resolver for the attemptReconnect mutation.
func (r *mutationResolver) AttemptReconnect(ctx context.Context) (model.ConnectionStatus, error) {
	telepresence.Connect()

	// Get updated connection status
	currentStatus := state.GlobalStore.GetTelepresenceStatus()
	return currentStatus, nil
}

// GetServices is the resolver for the getServices field.
func (r *queryResolver) GetServices(ctx context.Context) ([]*model.Service, error) {
	var out []*model.Service
	for _, svc := range state.GlobalStore.GetServices() {
		out = append(out, &model.Service{Name: svc.Name, URL: svc.URL, Target: model.ServiceTarget(svc.Target)})
	}
	return out, nil
}

// GetState is the resolver for the getState field.
func (r *queryResolver) GetState(ctx context.Context) (*model.State, error) {
	// Just return current state, don't trigger updates here
	return state.GlobalStore.GetState(), nil
}

// State is the resolver for the state field.
func (r *subscriptionResolver) State(ctx context.Context) (<-chan *model.State, error) {
	fmt.Printf("New state subscription created (active subscriptions: %d)\n", state.GlobalStore.GetStateSubscriberCount()+1)

	ch := state.GlobalStore.SubscribeToState()

	// Send current state immediately
	currentState := state.GlobalStore.GetState()
	select {
	case ch <- currentState:
	default:
	}

	// Remove the per-subscription ticker - the global ticker handles updates now
	go func() {
		defer fmt.Printf("State subscription ended\n")
		for {
			select {
			case <-ctx.Done():
				state.GlobalStore.UnsubscribeFromState(ch)
				return
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
