// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Config struct {
	Environments []*Environment `json:"environments"`
	Services     []*Service     `json:"services"`
}

type Environment struct {
	Name        string `json:"name"`
	KubeContext string `json:"kubeContext"`
}

type Mutation struct {
}

type Query struct {
}

type Service struct {
	Name   string        `json:"name"`
	URL    string        `json:"url"`
	Target ServiceTarget `json:"target"`
}

type ServiceTargetInput struct {
	Name   string        `json:"name"`
	Target ServiceTarget `json:"target"`
}

type State struct {
	TargetEnvironment *Environment     `json:"targetEnvironment"`
	Environments      []*Environment   `json:"environments"`
	Services          []*Service       `json:"services"`
	ConnectionStatus  ConnectionStatus `json:"connectionStatus"`
}

type Subscription struct {
}

type ConnectionStatus string

const (
	ConnectionStatusConnected    ConnectionStatus = "CONNECTED"
	ConnectionStatusDisconnected ConnectionStatus = "DISCONNECTED"
	ConnectionStatusConnecting   ConnectionStatus = "CONNECTING"
)

var AllConnectionStatus = []ConnectionStatus{
	ConnectionStatusConnected,
	ConnectionStatusDisconnected,
	ConnectionStatusConnecting,
}

func (e ConnectionStatus) IsValid() bool {
	switch e {
	case ConnectionStatusConnected, ConnectionStatusDisconnected, ConnectionStatusConnecting:
		return true
	}
	return false
}

func (e ConnectionStatus) String() string {
	return string(e)
}

func (e *ConnectionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionStatus", str)
	}
	return nil
}

func (e ConnectionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceTarget string

const (
	ServiceTargetLocal  ServiceTarget = "LOCAL"
	ServiceTargetRemote ServiceTarget = "REMOTE"
)

var AllServiceTarget = []ServiceTarget{
	ServiceTargetLocal,
	ServiceTargetRemote,
}

func (e ServiceTarget) IsValid() bool {
	switch e {
	case ServiceTargetLocal, ServiceTargetRemote:
		return true
	}
	return false
}

func (e ServiceTarget) String() string {
	return string(e)
}

func (e *ServiceTarget) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceTarget(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceTarget", str)
	}
	return nil
}

func (e ServiceTarget) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceTarget) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceTarget) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
